batch_size: 16
train_size: 0.7
val_size: 0.1
test_size: 0.2
val_start_date: '2023-01-01'
test_start_date: '2023-04-15'
context_length: 30
prediction_length: 15
max_lag: 1
start_date: '2020-01-01'
end_date: '2024-04-15'
target_transform: log
min_news: 300
max_news_daily: 5
min_trading_days: 365