dirs:
  data_dir: ./data
  source_dir: ./finformer
  source_data_dir: ./finformer/data
  source_model_dir: ./finformer/model
  fmp_dir: ./data/fmp
  raw_dataset_dir: ./data/raw-dataset
  dataset_dir: ./data/dataset
params:
  batch_size: 4
  context_length: 30
  prediction_length: 15
  max_lag: 1
  start_date: '2020-01-01'
  end_date: '2024-04-15'
  min_news: 300
  max_news_daily: 5
  min_trading_days: 365
sentiment_model:
  model:
    _target_: AutoModelForSequenceClassification
    name: ProsusAI/finbert
    pretrained: true
  output_size: 3
  max_batch_size: 16
  max_length: 128
time_series_model: 
  model:
    _target_: TimeSeriesTransformerModel
    name: null
  max_batch_size: 16
  embedding_dimension: 16
hf:
  dataset_dir: raw-dataset
  repo_id: halaction/finformer-data
fmp:
  metrics:
    dir: ./data/fmp/metrics
    separate: true
    endpoint: v3/key-metrics
    path_params:
      symbol: null
    query_params:
      apikey: null
      limit: null
      period: null
  news:
    dir: ./data/fmp/news
    separate: true
    endpoint: v3/stock_news
    path_params: null
    query_params:
      apikey: null
      limit: null
      page: null
      tickers: null
  prices:
    dir: ./data/fmp/prices
    separate: true
    endpoint: v3/historical-price-full
    path_params:
      symbol: null
    query_params:
      apikey: null
      from: null
      serietype: null
      to: null
  profile:
    dir: ./data/fmp/profile
    separate: false
    endpoint: v3/profile
    path_params:
      symbol: null
    query_params:
      apikey: null
features:
  dynamic_real_features:
  - revenuePerShare
  - netIncomePerShare
  - marketCap
  - peRatio
  - priceToSalesRatio
  - pocfratio
  - pfcfRatio
  - pbRatio
  - ptbRatio
  - debtToEquity
  - debtToAssets
  - currentRatio
  - interestCoverage
  - incomeQuality
  - salesGeneralAndAdministrativeToRevenue
  - researchAndDdevelopementToRevenue
  - intangiblesToTotalAssets
  - capexToOperatingCashFlow
  - capexToDepreciation
  - investedCapital
  static_categorical_features:
  - symbol
  - industry
  - sector
  - country
  static_real_features:
  - age_ipo
  time_features:
  - days_in_month
  - is_month_end
  - is_quarter_end
  - age
  - weekday_Monday
  - weekday_Saturday
  - weekday_Sunday
  - weekday_Thursday
  - weekday_Tuesday
  - weekday_Wednesday
  - month_August
  - month_December
  - month_February
  - month_January
  - month_July
  - month_June
  - month_March
  - month_May
  - month_November
  - month_October
  - month_September
  - quarter_2
  - quarter_3
  - quarter_4
  value_features:
  - open
  - close
  - low
  - high
  - volume
cardinality: null
