dynamic_real_features:
- revenuePerShare
- netIncomePerShare
- marketCap
- peRatio
- priceToSalesRatio
- pocfratio
- pfcfRatio
- pbRatio
- ptbRatio
- debtToEquity
- debtToAssets
- currentRatio
- interestCoverage
- incomeQuality
- salesGeneralAndAdministrativeToRevenue
- researchAndDdevelopementToRevenue
- intangiblesToTotalAssets
- capexToOperatingCashFlow
- capexToDepreciation
- investedCapital
static_categorical_features:
- symbol
- industry
- sector
- country
static_real_features:
- age_ipo
time_features:
- days_in_month
- is_month_end
- is_quarter_end
- age
- weekday_Monday
- weekday_Saturday
- weekday_Sunday
- weekday_Thursday
- weekday_Tuesday
- weekday_Wednesday
- month_August
- month_December
- month_February
- month_January
- month_July
- month_June
- month_March
- month_May
- month_November
- month_October
- month_September
- quarter_2
- quarter_3
- quarter_4
value_features:
- close