output_dir: trainer/full
overwrite_output_dir: true

report_to: 'wandb'
run_name: trainer-full

push_to_hub: true
hub_model_id: halaction/finformer-model
hub_strategy: checkpoint
hub_private_repo: false

prediction_loss_only: False
label_names: 
- future_values

per_device_train_batch_size: null
per_device_eval_batch_size: null

num_train_epochs: 10
max_steps: -1

learning_rate: 0.0003
weight_decay: 0.01
max_grad_norm: 1
gradient_accumulation_steps: 1

lr_scheduler_type: constant_with_warmup
warmup_steps: 300

#fp16: false
#half_precision_backend: auto

log_level: debug

logging_strategy: steps
logging_steps: 50

save_strategy: steps
save_steps: 500

evaluation_strategy: steps
eval_steps: 500
